#!/bin/zsh

branch_name=""
vis="private"


if [[ -z "$1" ]]; then
    echo "Usage: $0 branch_name"
    exit 1
fi

branch_name="$1"

git checkout -b "$branch_name"
git push --set-upstream origin "$branch_name"
