#!/bin/zsh

if [[ -z "$1" ]]; then
    echo "Usage: $(basename "$0") repo_name [(-P)ublic] "
    exit 1
fi

repo_name="$1"
vis="${2:-private}"


gh repo create "$repo_name" --"$vis"

if ! test -f ./README.md; then
    echo "# $repo_name" >> README.md
fi

git init
git add .
git commit -m "Initial commit"
git branch -M main
git remote add origin "https://github.com/jbrilha/$repo_name.git"
git push -u origin main
