#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else

selected=$(
    {
        find ~/.dotfiles -maxdepth 1 -type d \( -name ".git" \) -prune -o -type d -print;
        find ~/Developer -maxdepth 2 -type d -print;
        find ~/OneDrive/UNI/ANO3/SEMESTRE2 -mindepth 3 -maxdepth 3 -type d \( -name "testes" -o -name "teóricas" \) -prune -o -type d -print;


    } | fzf
)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
