#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else

selected=$(
    {
        find ~/.dotfiles \
            ~/Developer \
            ~/OneDrive/UNI/ANO3/SEMESTRE2/* \
            \( \
                -name ".git" -o \
                -name "flutter" -o \
                -path "*/testes/*" \
            \) -prune -o \
            -maxdepth 2 -type d \
            -print;
    } | fzf
)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

attached_clients=$(tmux list-clients -t $selected_name 2> /dev/null | wc -l)

if [[ -z $TMUX ]]; then
    if [ "$attached_clients" -eq 0 ]; then
        tmux attach-session -t $selected_name
    else
        tmux new-session -t $selected_name
    fi
else
    tmux switch-client -t $selected_name
fi

# if [[ -z $TMUX ]]; then
#     tmux attach-session -t $selected_name
# else
#     tmux switch-client -t $selected_name
# fi
